--cau 1
CREATE or alter PROCEDURE Seen_1 
AS
BEGIN
	SET NOCOUNT ON;
	SELECT DAT_PHONG.MADATPHONG, DAT_PHONG.MAPHONG, DAT_PHONG.MAKH, DAT_PHONG.NGAYDAT, DAT_PHONG.GIOBATDAU, DAT_PHONG.GIOKETTHUC
	FROM   DAT_PHONG INNER JOIN
             PHONG ON DAT_PHONG.MAPHONG = PHONG.MAPHONG
	WHERE DATEPART(HH ,DAT_PHONG.GIOBATDAU)>18 and PHONG.SOKHACHTOIDA>15		
END
GO
--CAU 2
DECLARE @MaDV int, @SoLuong int
PRINT N'--------------SỐ LƯỢNG CỦA MỖI DỊCH VỤ-----------------'
DECLARE SLDV_cursor CURSOR FOR 
	SELECT DVDK.MADV, SUM(CTSDDV.SOLUONG) AS SOLuong FROM DAT_PHONG DP
	INNER JOIN CHI_TIET_SU_DUNG_DV CTSDDV ON CTSDDV.MADATPHONG = DP.MADATPHONG
	INNER JOIN DICH_VU_DI_KEM DVDK ON DVDK.MADV = CTSDDV.MADV
	WHERE MONTH(DP.NGAYDAT) = 3 AND YEAR(DP.NGAYDAT) = 2018 AND DP.TRANGTHAIDAT = N'DA DAT'
	GROUP BY DVDK.MADV
OPEN SLDV_cursor
FETCH NEXT FROM SLDV_cursor
INTO @MaDV, @SoLuong
PRINT N'Mã Dịch Vụ		Số lượng sử dụng'
WHILE @@FETCH_STATUS = 0
BEGIN
	print N'	' + CAST(@MaDV as nvarchar(max)) +
		N'				' + CAST(@SoLuong as nvarchar(max))

	FETCH NEXT FROM SLDV_cursor 
		INTO @MaDV, @SoLuong
END
CLOSE SLDV_cursor
DEALLOCATE SLDV_cursor
GO
--CAU 3
CREATE or alter FUNCTION DOANH_THU 
(	
	@maphong int 
)
RETURNS TABLE 
AS
RETURN 
(
select c.maphong , (z.PP + z.PDV) as Thanh_Tien
from (select a.MAPHONG ,m.PDV ,sum(datediff(HH , b.GIOBATDAU , b.GIOKETTHUC)* a.GIAPHONG) as PP
		from (select  PHONG.MAPHONG,sum(CHI_TIET_SU_DUNG_DV.SOLUONG * DICH_VU_DI_KEM.DONGIA) as PDV
			from CHI_TIET_SU_DUNG_DV , DICH_VU_DI_KEM , PHONG , DAT_PHONG
			where CHI_TIET_SU_DUNG_DV.MADV=DICH_VU_DI_KEM.MADV and CHI_TIET_SU_DUNG_DV.MADATPHONG=DAT_PHONG.MADATPHONG 
					and DAT_PHONG.MAPHONG = PHONG.MAPHONG and DAT_PHONG.TRANGTHAIDAT= 'DA DAT'
			group by PHONG.MAPHONG) m , PHONG a , DAT_PHONG b
		where a.MAPHONG = b.MAPHONG and a.MAPHONG = m.MAPHONG and b.TRANGTHAIDAT='DA DAT'
		group by a.MAPHONG,m.pdv) z , PHONG c,DAT_PHONG d
where c.MAPHONG = z.MAPHONG and z.MAPHONG =d.MAPHONG and d.TRANGTHAIDAT= 'DA DAT' and z.MAPHONG =@maphong 
group by c.MAPHONG ,z.PP ,z.PDV 
)
GO
--SELECT *FROM DBO.DOANH_THU (1)
select *from DAT_PHONG
